### ISSUE TITLE
eCommerceCart Details hk.

### ISSUE THREAD

**Issue by mahirkursun** [muratokur3/ecommercecart#5]
Selamlar Murat,

- Projede sepet detayını görüntülemek için bir sayfa oluşturmamız gerekiyor.
- Components dosyası içerisinde sepet detayını temsil edecek bir React bileşeni oluştur Örneğin, cartDetailsView adında bir bileşen oluşturabilirsin.
-  Sepet içeriğini listele ve her ürünün adı, fiyatı, miktarı gibi bilgilerini göster. Silme işlemi de bu sayfada olacak. Ek olarak görselde eklenebilir(tercihe bağlı)
- Tasarım olarak sayfanın ortasında olacak ve listelenecek. Renk ve tasarım tercihe bağlı olacak.
- Veri aktarımı props konusunda, tasarım bittikten sonra ben yardımcı olacağım. 

Teşekkürler.
İyi çalışmalar.

**Comment by muratokur3** [comment]
Selamlar Mahir,
 
   En kısa zamanda commit ederim.

Teşekkürler,
Mutlu çalışmalar.
